CREATE TABLE tbl_Cervejaria
(
    ID_CERVEJARIA INTEGER NOT NULL
GENERATED ALWAYS AS IDENTITY
(START WITH 1, INCREMENT BY 1)
CONSTRAINT PK_Cervejaria PRIMARY KEY,
    CERVEJARIA VARCHAR(60) NOT NULL,
    PAIS VARCHAR(60) NOT NULL
    );

CREATE TABLE tbl_Cerveja
(
    ID_CERVEJA INTEGER NOT NULL
GENERATED ALWAYS AS IDENTITY
(START WITH 1, INCREMENT BY 1)
CONSTRAINT PK_Cerveja PRIMARY KEY,
    ID_CERVEJARIA INTEGER NOT NULL,
    ROTULO VARCHAR(60) NOT NULL,
    PRECO VARCHAR(6) NOT NULL,
    VOLUME VARCHAR(5) NOT NULL,
    TEOR VARCHAR(3) NOT NULL,
    COR VARCHAR(7) NOT NULL,
    TEMPERATURA VARCHAR(6) NOT NULL,
    FAMILIA_E_ESTILO VARCHAR(60) NOT NULL,
    DESCRICAO VARCHAR(150) NOT NULL,
    SABOR VARCHAR(150) NOT NULL,
    IMAGEM_1 VARCHAR(60) NOT NULL,
    IMAGEM_2 VARCHAR(60) NOT NULL,
    IMAGEM_3 VARCHAR(60) NOT NULL
);

ALTER TABLE tbl_Cerveja ADD
CONSTRAINT FK_ID_CERVEJARIA FOREIGN KEY
(ID_CERVEJARIA) REFERENCES
tbl_Cervejaria(ID_CERVEJARIA);

CREATE TABLE tbl_Estoque
(
	ID_ESTOQUE INTEGER NOT NULL
GENERATED ALWAYS AS IDENTITY
(START WITH 1, INCREMENT BY 1)
CONSTRAINT PK_Estoque PRIMARY KEY,
ID_CERVEJA INTEGER NOT NULL,
QUANTIDADE INTEGER NOT NULL,
PORCENTAGEM DOUBLE NOT NULL,
ESTOQUE_MINIMO INTEGER NOT NULL,
ESTOQUE_MAXIMO INTEGER NOT NULL,
PRECO_AQUISICAO DOUBLE NOT NULL,
LUCRO DOUBLE NOT NULL,
DISPONIBILIDADE INTEGER NOT NULL
);

ALTER TABLE tbl_Estoque ADD
CONSTRAINT FK_ID_CERVEJA FOREIGN KEY
(ID_CERVEJA) REFERENCES
tbl_Cerveja(ID_CERVEJA);
CREATE TABLE tbl_EntradaEstoque
(

	ID_ENTRADAESTOQUE INTEGER NOT NULL
GENERATED ALWAYS AS IDENTITY
(START WITH 1, INCREMENT BY 1)
CONSTRAINT PK_EntradaEstoque PRIMARY KEY,
ID_FUNCIONARIO INTEGER NOT NULL,
DATA_MODIFICACAO VARCHAR(60) NOT NULL,
ID_ESTOQUE INTEGER NOT NULL,
ID_CERVEJA INTEGER NOT NULL,
ALTERACOES VARCHAR(200) NOT NULL
);

CREATE TABLE tbl_SaidaEstoque
(
	ID_SAIDAESTOQUE INTEGER NOT NULL
GENERATED ALWAYS AS IDENTITY
(START WITH 1, INCREMENT BY 1)
CONSTRAINT PK_SaidaEstoque PRIMARY KEY,
ID_CLIENTE INTEGER NOT NULL,
DATA_COMPRA VARCHAR(60) NOT NULL,
ID_ESTOQUE INTEGER NOT NULL,
ID_CERVEJA INTEGER NOT NULL,
QUANTIDADE INTEGER NOT NULL,
PRECO VARCHAR(6) NOT NULL,
VALOR_TOTAL VARCHAR(8) NOT NULL,
DEDUCAO VARCHAR(2) NOT NULL
);

CREATE TABLE tbl_ListaDeDesejos
(
    ID_ITEM INTEGER NOT NULL
GENERATED ALWAYS AS IDENTITY
(START WITH 1, INCREMENT BY 1)
CONSTRAINT PK_Item PRIMARY KEY,
    ID_CLIENTE INTEGER NOT NULL,
    ID_CERVEJA INTEGER NOT NULL
    );